onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate /synthi_top_tb/DUT/reg_controller_1/clk_6m
add wave -noupdate /synthi_top_tb/DUT/reg_controller_1/rst_n
add wave -noupdate -radix hexadecimal /synthi_top_tb/DUT/reg_controller_1/data_i
add wave -noupdate /synthi_top_tb/DUT/reg_controller_1/data_rdy
add wave -noupdate -radix hexadecimal -childformat {{/synthi_top_tb/DUT/reg_controller_1/reg(0) -radix hexadecimal} {/synthi_top_tb/DUT/reg_controller_1/reg(1) -radix hexadecimal} {/synthi_top_tb/DUT/reg_controller_1/reg(2) -radix hexadecimal} {/synthi_top_tb/DUT/reg_controller_1/reg(3) -radix hexadecimal} {/synthi_top_tb/DUT/reg_controller_1/reg(4) -radix hexadecimal} {/synthi_top_tb/DUT/reg_controller_1/reg(5) -radix hexadecimal} {/synthi_top_tb/DUT/reg_controller_1/reg(6) -radix hexadecimal} {/synthi_top_tb/DUT/reg_controller_1/reg(7) -radix hexadecimal} {/synthi_top_tb/DUT/reg_controller_1/reg(8) -radix hexadecimal} {/synthi_top_tb/DUT/reg_controller_1/reg(9) -radix hexadecimal} {/synthi_top_tb/DUT/reg_controller_1/reg(10) -radix hexadecimal} {/synthi_top_tb/DUT/reg_controller_1/reg(11) -radix hexadecimal} {/synthi_top_tb/DUT/reg_controller_1/reg(12) -radix hexadecimal} {/synthi_top_tb/DUT/reg_controller_1/reg(13) -radix hexadecimal} {/synthi_top_tb/DUT/reg_controller_1/reg(14) -radix hexadecimal} {/synthi_top_tb/DUT/reg_controller_1/reg(15) -radix hexadecimal}} -expand -subitemconfig {/synthi_top_tb/DUT/reg_controller_1/reg(0) {-height 15 -radix hexadecimal} /synthi_top_tb/DUT/reg_controller_1/reg(1) {-height 15 -radix hexadecimal} /synthi_top_tb/DUT/reg_controller_1/reg(2) {-height 15 -radix hexadecimal} /synthi_top_tb/DUT/reg_controller_1/reg(3) {-height 15 -radix hexadecimal} /synthi_top_tb/DUT/reg_controller_1/reg(4) {-height 15 -radix hexadecimal} /synthi_top_tb/DUT/reg_controller_1/reg(5) {-height 15 -radix hexadecimal} /synthi_top_tb/DUT/reg_controller_1/reg(6) {-height 15 -radix hexadecimal} /synthi_top_tb/DUT/reg_controller_1/reg(7) {-height 15 -radix hexadecimal} /synthi_top_tb/DUT/reg_controller_1/reg(8) {-height 15 -radix hexadecimal} /synthi_top_tb/DUT/reg_controller_1/reg(9) {-height 15 -radix hexadecimal} /synthi_top_tb/DUT/reg_controller_1/reg(10) {-height 15 -radix hexadecimal} /synthi_top_tb/DUT/reg_controller_1/reg(11) {-height 15 -radix hexadecimal} /synthi_top_tb/DUT/reg_controller_1/reg(12) {-height 15 -radix hexadecimal} /synthi_top_tb/DUT/reg_controller_1/reg(13) {-height 15 -radix hexadecimal} /synthi_top_tb/DUT/reg_controller_1/reg(14) {-height 15 -radix hexadecimal} /synthi_top_tb/DUT/reg_controller_1/reg(15) {-height 15 -radix hexadecimal}} /synthi_top_tb/DUT/reg_controller_1/reg
add wave -noupdate -radix hexadecimal -childformat {{/synthi_top_tb/DUT/reg_controller_1/config_i(0) -radix hexadecimal} {/synthi_top_tb/DUT/reg_controller_1/config_i(1) -radix hexadecimal} {/synthi_top_tb/DUT/reg_controller_1/config_i(2) -radix hexadecimal} {/synthi_top_tb/DUT/reg_controller_1/config_i(3) -radix hexadecimal} {/synthi_top_tb/DUT/reg_controller_1/config_i(4) -radix hexadecimal} {/synthi_top_tb/DUT/reg_controller_1/config_i(5) -radix hexadecimal} {/synthi_top_tb/DUT/reg_controller_1/config_i(6) -radix hexadecimal} {/synthi_top_tb/DUT/reg_controller_1/config_i(7) -radix hexadecimal} {/synthi_top_tb/DUT/reg_controller_1/config_i(8) -radix hexadecimal} {/synthi_top_tb/DUT/reg_controller_1/config_i(9) -radix hexadecimal} {/synthi_top_tb/DUT/reg_controller_1/config_i(10) -radix hexadecimal} {/synthi_top_tb/DUT/reg_controller_1/config_i(11) -radix hexadecimal} {/synthi_top_tb/DUT/reg_controller_1/config_i(12) -radix hexadecimal} {/synthi_top_tb/DUT/reg_controller_1/config_i(13) -radix hexadecimal} {/synthi_top_tb/DUT/reg_controller_1/config_i(14) -radix hexadecimal} {/synthi_top_tb/DUT/reg_controller_1/config_i(15) -radix hexadecimal}} -expand -subitemconfig {/synthi_top_tb/DUT/reg_controller_1/config_i(0) {-height 15 -radix hexadecimal} /synthi_top_tb/DUT/reg_controller_1/config_i(1) {-height 15 -radix hexadecimal} /synthi_top_tb/DUT/reg_controller_1/config_i(2) {-height 15 -radix hexadecimal} /synthi_top_tb/DUT/reg_controller_1/config_i(3) {-height 15 -radix hexadecimal} /synthi_top_tb/DUT/reg_controller_1/config_i(4) {-height 15 -radix hexadecimal} /synthi_top_tb/DUT/reg_controller_1/config_i(5) {-height 15 -radix hexadecimal} /synthi_top_tb/DUT/reg_controller_1/config_i(6) {-height 15 -radix hexadecimal} /synthi_top_tb/DUT/reg_controller_1/config_i(7) {-height 15 -radix hexadecimal} /synthi_top_tb/DUT/reg_controller_1/config_i(8) {-height 15 -radix hexadecimal} /synthi_top_tb/DUT/reg_controller_1/config_i(9) {-height 15 -radix hexadecimal} /synthi_top_tb/DUT/reg_controller_1/config_i(10) {-height 15 -radix hexadecimal} /synthi_top_tb/DUT/reg_controller_1/config_i(11) {-height 15 -radix hexadecimal} /synthi_top_tb/DUT/reg_controller_1/config_i(12) {-height 15 -radix hexadecimal} /synthi_top_tb/DUT/reg_controller_1/config_i(13) {-height 15 -radix hexadecimal} /synthi_top_tb/DUT/reg_controller_1/config_i(14) {-height 15 -radix hexadecimal} /synthi_top_tb/DUT/reg_controller_1/config_i(15) {-height 15 -radix hexadecimal}} /synthi_top_tb/DUT/reg_controller_1/config_i
add wave -noupdate -radix hexadecimal -childformat {{/synthi_top_tb/DUT/reg_controller_1/config_o(0) -radix hexadecimal} {/synthi_top_tb/DUT/reg_controller_1/config_o(1) -radix hexadecimal} {/synthi_top_tb/DUT/reg_controller_1/config_o(2) -radix hexadecimal} {/synthi_top_tb/DUT/reg_controller_1/config_o(3) -radix hexadecimal} {/synthi_top_tb/DUT/reg_controller_1/config_o(4) -radix hexadecimal} {/synthi_top_tb/DUT/reg_controller_1/config_o(5) -radix hexadecimal} {/synthi_top_tb/DUT/reg_controller_1/config_o(6) -radix hexadecimal} {/synthi_top_tb/DUT/reg_controller_1/config_o(7) -radix hexadecimal} {/synthi_top_tb/DUT/reg_controller_1/config_o(8) -radix hexadecimal} {/synthi_top_tb/DUT/reg_controller_1/config_o(9) -radix hexadecimal} {/synthi_top_tb/DUT/reg_controller_1/config_o(10) -radix hexadecimal} {/synthi_top_tb/DUT/reg_controller_1/config_o(11) -radix hexadecimal} {/synthi_top_tb/DUT/reg_controller_1/config_o(12) -radix hexadecimal} {/synthi_top_tb/DUT/reg_controller_1/config_o(13) -radix hexadecimal} {/synthi_top_tb/DUT/reg_controller_1/config_o(14) -radix hexadecimal} {/synthi_top_tb/DUT/reg_controller_1/config_o(15) -radix hexadecimal}} -expand -subitemconfig {/synthi_top_tb/DUT/reg_controller_1/config_o(0) {-height 15 -radix hexadecimal} /synthi_top_tb/DUT/reg_controller_1/config_o(1) {-height 15 -radix hexadecimal} /synthi_top_tb/DUT/reg_controller_1/config_o(2) {-height 15 -radix hexadecimal} /synthi_top_tb/DUT/reg_controller_1/config_o(3) {-height 15 -radix hexadecimal} /synthi_top_tb/DUT/reg_controller_1/config_o(4) {-height 15 -radix hexadecimal} /synthi_top_tb/DUT/reg_controller_1/config_o(5) {-height 15 -radix hexadecimal} /synthi_top_tb/DUT/reg_controller_1/config_o(6) {-height 15 -radix hexadecimal} /synthi_top_tb/DUT/reg_controller_1/config_o(7) {-height 15 -radix hexadecimal} /synthi_top_tb/DUT/reg_controller_1/config_o(8) {-height 15 -radix hexadecimal} /synthi_top_tb/DUT/reg_controller_1/config_o(9) {-height 15 -radix hexadecimal} /synthi_top_tb/DUT/reg_controller_1/config_o(10) {-height 15 -radix hexadecimal} /synthi_top_tb/DUT/reg_controller_1/config_o(11) {-height 15 -radix hexadecimal} /synthi_top_tb/DUT/reg_controller_1/config_o(12) {-height 15 -radix hexadecimal} /synthi_top_tb/DUT/reg_controller_1/config_o(13) {-height 15 -radix hexadecimal} /synthi_top_tb/DUT/reg_controller_1/config_o(14) {-height 15 -radix hexadecimal} /synthi_top_tb/DUT/reg_controller_1/config_o(15) {-height 15 -radix hexadecimal}} /synthi_top_tb/DUT/reg_controller_1/config_o
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {1287343 ns} 0}
quietly wave cursor active 1
configure wave -namecolwidth 507
configure wave -valuecolwidth 258
configure wave -justifyvalue left
configure wave -signalnamewidth 0
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ns
update
WaveRestoreZoom {0 ns} {1756272 ns}
