onerror {resume}
quietly virtual signal -install /synthi_top_tb/DUT/tone_gen_1/fm_dds_inst_gen(0)/inst_fm_dds/dds_car_1 { /synthi_top_tb/DUT/tone_gen_1/fm_dds_inst_gen(0)/inst_fm_dds/dds_car_1/count(18 downto 11)} count_new
quietly virtual signal -install /synthi_top_tb/DUT/tone_gen_1/fm_dds_inst_gen(0)/inst_fm_dds/dds_car_1 { /synthi_top_tb/DUT/tone_gen_1/fm_dds_inst_gen(0)/inst_fm_dds/dds_car_1/phi_incr_i(18 downto 11)} phi_incr
quietly WaveActivateNextPane {} 0
add wave -noupdate -radix decimal -childformat {{/synthi_top_tb/DUT/tone_gen_1/dds_o_array(0) -radix decimal} {/synthi_top_tb/DUT/tone_gen_1/dds_o_array(1) -radix decimal} {/synthi_top_tb/DUT/tone_gen_1/dds_o_array(2) -radix decimal} {/synthi_top_tb/DUT/tone_gen_1/dds_o_array(3) -radix decimal} {/synthi_top_tb/DUT/tone_gen_1/dds_o_array(4) -radix decimal} {/synthi_top_tb/DUT/tone_gen_1/dds_o_array(5) -radix decimal} {/synthi_top_tb/DUT/tone_gen_1/dds_o_array(6) -radix decimal} {/synthi_top_tb/DUT/tone_gen_1/dds_o_array(7) -radix decimal} {/synthi_top_tb/DUT/tone_gen_1/dds_o_array(8) -radix decimal} {/synthi_top_tb/DUT/tone_gen_1/dds_o_array(9) -radix decimal}} -expand -subitemconfig {/synthi_top_tb/DUT/tone_gen_1/dds_o_array(0) {-format Analog-Step -height 74 -max 3963.0000000000009 -min -3968.0 -radix decimal} /synthi_top_tb/DUT/tone_gen_1/dds_o_array(1) {-format Analog-Step -height 74 -max 3908.9999999999995 -min -3927.0 -radix decimal} /synthi_top_tb/DUT/tone_gen_1/dds_o_array(2) {-format Analog-Step -height 74 -max 3581.0000000000005 -min -3584.0 -radix decimal} /synthi_top_tb/DUT/tone_gen_1/dds_o_array(3) {-format Analog-Step -height 74 -max 3924.0 -min -3942.0 -radix decimal} /synthi_top_tb/DUT/tone_gen_1/dds_o_array(4) {-format Analog-Step -height 74 -max 70.0 -radix decimal} /synthi_top_tb/DUT/tone_gen_1/dds_o_array(5) {-format Analog-Step -height 74 -max 70.0 -radix decimal} /synthi_top_tb/DUT/tone_gen_1/dds_o_array(6) {-format Analog-Step -height 74 -max 70.0 -radix decimal} /synthi_top_tb/DUT/tone_gen_1/dds_o_array(7) {-format Analog-Step -height 74 -max 70.0 -radix decimal} /synthi_top_tb/DUT/tone_gen_1/dds_o_array(8) {-format Analog-Step -height 74 -max 70.0 -radix decimal} /synthi_top_tb/DUT/tone_gen_1/dds_o_array(9) {-format Analog-Step -height 74 -max 70.0 -radix decimal}} /synthi_top_tb/DUT/tone_gen_1/dds_o_array
add wave -noupdate /synthi_top_tb/DUT/tone_gen_1/dds_used_o
add wave -noupdate /synthi_top_tb/DUT/midi_controller_fsm_1/note_on
add wave -noupdate -childformat {{/synthi_top_tb/DUT/midi_controller_fsm_1/note_o(0) -radix unsigned} {/synthi_top_tb/DUT/midi_controller_fsm_1/note_o(1) -radix unsigned} {/synthi_top_tb/DUT/midi_controller_fsm_1/note_o(2) -radix unsigned} {/synthi_top_tb/DUT/midi_controller_fsm_1/note_o(3) -radix unsigned} {/synthi_top_tb/DUT/midi_controller_fsm_1/note_o(4) -radix unsigned} {/synthi_top_tb/DUT/midi_controller_fsm_1/note_o(5) -radix unsigned} {/synthi_top_tb/DUT/midi_controller_fsm_1/note_o(6) -radix unsigned} {/synthi_top_tb/DUT/midi_controller_fsm_1/note_o(7) -radix unsigned} {/synthi_top_tb/DUT/midi_controller_fsm_1/note_o(8) -radix unsigned} {/synthi_top_tb/DUT/midi_controller_fsm_1/note_o(9) -radix unsigned}} -subitemconfig {/synthi_top_tb/DUT/midi_controller_fsm_1/note_o(0) {-height 15 -radix unsigned} /synthi_top_tb/DUT/midi_controller_fsm_1/note_o(1) {-height 15 -radix unsigned} /synthi_top_tb/DUT/midi_controller_fsm_1/note_o(2) {-height 15 -radix unsigned} /synthi_top_tb/DUT/midi_controller_fsm_1/note_o(3) {-height 15 -radix unsigned} /synthi_top_tb/DUT/midi_controller_fsm_1/note_o(4) {-height 15 -radix unsigned} /synthi_top_tb/DUT/midi_controller_fsm_1/note_o(5) {-height 15 -radix unsigned} /synthi_top_tb/DUT/midi_controller_fsm_1/note_o(6) {-height 15 -radix unsigned} /synthi_top_tb/DUT/midi_controller_fsm_1/note_o(7) {-height 15 -radix unsigned} /synthi_top_tb/DUT/midi_controller_fsm_1/note_o(8) {-height 15 -radix unsigned} /synthi_top_tb/DUT/midi_controller_fsm_1/note_o(9) {-height 15 -radix unsigned}} /synthi_top_tb/DUT/midi_controller_fsm_1/note_o
add wave -noupdate -childformat {{/synthi_top_tb/DUT/midi_controller_fsm_1/velocity(0) -radix unsigned} {/synthi_top_tb/DUT/midi_controller_fsm_1/velocity(1) -radix unsigned} {/synthi_top_tb/DUT/midi_controller_fsm_1/velocity(2) -radix unsigned} {/synthi_top_tb/DUT/midi_controller_fsm_1/velocity(3) -radix unsigned} {/synthi_top_tb/DUT/midi_controller_fsm_1/velocity(4) -radix unsigned} {/synthi_top_tb/DUT/midi_controller_fsm_1/velocity(5) -radix unsigned} {/synthi_top_tb/DUT/midi_controller_fsm_1/velocity(6) -radix unsigned} {/synthi_top_tb/DUT/midi_controller_fsm_1/velocity(7) -radix unsigned} {/synthi_top_tb/DUT/midi_controller_fsm_1/velocity(8) -radix unsigned} {/synthi_top_tb/DUT/midi_controller_fsm_1/velocity(9) -radix unsigned}} -subitemconfig {/synthi_top_tb/DUT/midi_controller_fsm_1/velocity(0) {-height 15 -radix unsigned} /synthi_top_tb/DUT/midi_controller_fsm_1/velocity(1) {-height 15 -radix unsigned} /synthi_top_tb/DUT/midi_controller_fsm_1/velocity(2) {-height 15 -radix unsigned} /synthi_top_tb/DUT/midi_controller_fsm_1/velocity(3) {-height 15 -radix unsigned} /synthi_top_tb/DUT/midi_controller_fsm_1/velocity(4) {-height 15 -radix unsigned} /synthi_top_tb/DUT/midi_controller_fsm_1/velocity(5) {-height 15 -radix unsigned} /synthi_top_tb/DUT/midi_controller_fsm_1/velocity(6) {-height 15 -radix unsigned} /synthi_top_tb/DUT/midi_controller_fsm_1/velocity(7) {-height 15 -radix unsigned} /synthi_top_tb/DUT/midi_controller_fsm_1/velocity(8) {-height 15 -radix unsigned} /synthi_top_tb/DUT/midi_controller_fsm_1/velocity(9) {-height 15 -radix unsigned}} /synthi_top_tb/DUT/midi_controller_fsm_1/velocity
add wave -noupdate -label count -radix unsigned /synthi_top_tb/DUT/tone_gen_1/fm_dds_inst_gen(0)/inst_fm_dds/dds_car_1/count_new
add wave -noupdate -radix unsigned /synthi_top_tb/DUT/tone_gen_1/fm_dds_inst_gen(0)/inst_fm_dds/dds_car_1/phi_incr
add wave -noupdate /synthi_top_tb/DUT/tone_gen_1/fm_dds_inst_gen(0)/inst_fm_dds/dds_car_1/attenu_i
add wave -noupdate -format Analog-Step -height 74 -max 9977.0000000000018 -min -11590.0 -radix decimal /synthi_top_tb/DUT/tone_gen_1/dds_l_o
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {23390714 ns} 0}
quietly wave cursor active 1
configure wave -namecolwidth 507
configure wave -valuecolwidth 258
configure wave -justifyvalue left
configure wave -signalnamewidth 0
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ns
update
WaveRestoreZoom {11862151 ns} {27414583 ns}
